require('dotenv').config();
const { Client } = require('pg');

async function setup() {
  // Connect without specifying DB first so we can create it
  const client = new Client({
    host:     process.env.DB_HOST     || 'localhost',
    port:     parseInt(process.env.DB_PORT) || 5432,
    database: 'postgres',
    user:     process.env.DB_USER     || 'postgres',
    password: process.env.DB_PASSWORD || '',
  });

  const dbName = process.env.DB_NAME || 'bankdatapetanew';

  try {
    await client.connect();
    console.log('Connected to PostgreSQL.');

    // Create database if not exists
    const exists = await client.query(
      `SELECT 1 FROM pg_database WHERE datname = $1`, [dbName]
    );
    if (exists.rowCount === 0) {
      await client.query(`CREATE DATABASE "${dbName}"`);
      console.log(`Database "${dbName}" created.`);
    } else {
      console.log(`Database "${dbName}" already exists.`);
    }

    await client.end();

    // Now connect to the target DB and create tables
    const db = new Client({
      host:     process.env.DB_HOST     || 'localhost',
      port:     parseInt(process.env.DB_PORT) || 5432,
      database: dbName,
      user:     process.env.DB_USER     || 'postgres',
      password: process.env.DB_PASSWORD || '',
    });

    await db.connect();

    await db.query(`
      CREATE TABLE IF NOT EXISTS maps (
        id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name         TEXT NOT NULL,
        notes        TEXT NOT NULL DEFAULT '',
        filename     TEXT NOT NULL,
        original_name TEXT NOT NULL,
        file_size    BIGINT NOT NULL DEFAULT 0,
        uploaded_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at   TIMESTAMPTZ
      );
    `);
    console.log('Table "maps" ready.');

    await db.query(`
      CREATE TABLE IF NOT EXISTS road_pins (
        id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        map_id      BIGINT NOT NULL REFERENCES maps(id) ON DELETE CASCADE,
        road_name   TEXT NOT NULL,
        notes       TEXT NOT NULL DEFAULT '',
        x_pct       NUMERIC(6,3) NOT NULL,
        y_pct       NUMERIC(6,3) NOT NULL,
        created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at  TIMESTAMPTZ
      );
    `);
    console.log('Table "road_pins" ready.');

    await db.query(`
      CREATE INDEX IF NOT EXISTS idx_road_pins_map_id ON road_pins(map_id);
    `);

    await db.end();
    console.log('\nDatabase setup complete. Run "npm start" to launch the app.');
  } catch (err) {
    console.error('\nSetup failed:', err.message);
    console.error('Check your .env credentials and make sure PostgreSQL is running.');
    process.exit(1);
  }
}

setup();
